### ISSUE TITLE
Coveralls repo token to be provided for the repositories.

### ISSUE THREAD

**Issue by rmathew1011** [TAMULib/.github#1]
Requesting COVERALLS_REPO_TOKEN for the repositories:
- [x] [ProjectManagementUI](https://github.com/TAMULib/ProjectManagementUI)
- [x] [ProjectManagementService](https://github.com/TAMULib/ProjectManagementService)
- [x] [LibraryServiceStatusSystemUI](https://github.com/TAMULib/LibraryServiceStatusSystemUI)
- [x] [LibraryServiceStatusSystemService](https://github.com/TAMULib/LibraryServiceStatusSystemService)
- [x] [CAP](https://github.com/TAMULib/CAP)
- [x] [MetadataAssignmentToolUI](https://github.com/TAMULib/MetadataAssignmentToolUI)
- [x] [MetadataAssignmentToolService](https://github.com/TAMULib/MetadataAssignmentToolService)
- [x] [GIFMButtonUI](https://github.com/TAMULib/GIFMButtonUI)
- [x] [GIFMButtonService](https://github.com/TAMULib/GIFMButtonService)
- [x] [IRIIIFService](https://github.com/TAMULib/IRIIIFService)

**Comment by ghost** [comment]
Closing. Is not necessary.
